import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"

const pally = localFont({
  src: '/fonts/Pally-Variable.woff2',
  variable: '--font-pally',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pally.variable}>
      <body>{children}</body>
    </html>
  );
}
